#!/bin/bash

echo '输入 1 到 5 之间的数字:'
echo '你输入的数字为:'
read aNum
case $aNum in
    1)  echo '你选择了 1'
    ;;
    2)  echo '你选择了 2'
    ;;
    3)  echo '你选择了 3'
    ;;
    4|5)  echo '你选择了 4 或者 5'
    ;;
    *)  echo '你没有输入 1 到 5 之间的数字'
    ;;
esac
